### ISSUE TITLE
JT808解析异常

### ISSUE THREAD

**Issue by lishewen** [SmallChi/JTTools#4]
设备上来的原始报文：
7E 02 00 00 57 00 00 00 00 77 77 62 F7 00 08 00 00 00 04 00 03 01 66 53 A7 06 A2 55 F8 00 9E 00 00 00 00 20 03 31 07 00 35 01 04 00 00 00 00 03 02 00 00 21 08 00 00 00 A0 00 05 6F 67 25 04 00 00 00 00 2B 04 00 00 00 00 30 01 03 31 01 0C 16 04 00 00 0B FE 17 01 02 18 04 01 1D 00 00 14 04 00 00 00 02 8A 7E

**Comment by SmallChi** [comment]
你这边是不是自定义附加信息Id的时候占用了1078扩展808的附加信息Id?

**Comment by lishewen** [comment]
终端设备不是我们的，对方说没有，我其实也不知道有没有[捂脸]

**Comment by SmallChi** [comment]
现在是可以解析了，临时把1078的模块去掉了，旧版不在维护了，新版再统一加上去。

**Comment by lishewen** [comment]
好的，谢谢
