### ISSUE TITLE
JT808分析工具无法解析1078协议

### ISSUE THREAD

**Issue by grapeqin** [SmallChi/JTTools#5]
hello，today when i use JT808 tools but find it can not parse 1078，some day ago it runs。

**Comment by SmallChi** [comment]
有没有具体的数据包？可以解析的，要先选择扩展类型（国标808【默认】、扩展1078、扩展主动安全）。
![808_1078](https://user-images.githubusercontent.com/12674769/85404807-13303300-b592-11ea-8417-2be5e9a904de.png)

**Comment by grapeqin** [comment]
感谢，感谢，昨晚可能是我的浏览器有问题，选择扩展1078的时候一直自动跳到国标808，刚才试验了下确实可以了。
