### ISSUE TITLE
jt809分析工具2019版本，对于“车辆定位信息内容”没有具体解析

### ISSUE THREAD

**Issue by tmljob** [SmallChi/JTTools#7]
如下图
![image](https://user-images.githubusercontent.com/69188034/134837270-3a10f3bd-d1f6-475b-af59-bdf837f32a0e.png)
报文如下：
5B000000C9000006821200013415F4010000000000270F000000005EA507B8D4C1413132333435000000000000000000000000000212020000008B0000000026000000010000000200BA7F0E07E4F11C0028003C00001810151010100104000000640202007D000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000C2ED5D

希望能对“车辆定位信息内容”具体解析。

**Comment by SmallChi** [comment]
@tmljob 已支持。
